### ISSUE TITLE
Таблиця сайтів

### ISSUE THREAD

**Issue by olesmartyniuk** [olesmartyniuk/russian-sites-status-ui#1]
Зверстати таблицю сайтів зі загальною інформацією по статусу:

1. Назва сайту
2. Статус
3. Аптайм за останній день

Path: /sites
Component: SitesListComponent

**Comment by Pavlo-0** [comment]
Done

**Comment by olesmartyniuk** [comment]
Круто! 

Можна попросити дещо змінити? 

1. Давай зробимо дві іконки червону і зелену для up і down замість тексту. В хінті над іконкою можна написати типу "Сайт доступний" або "Сайт недоступний"
2. Давай приберемо рамку у таблиці, вона дисонує з рамкою навколо сторінки з контентом.
3. Давай додамо хінт над полем Uptime типу "Сайт доступний N% часу за останній день", щоб розуміти що це за відсоток.
