### ISSUE TITLE
Дизайн сторінки з деталями про сайт

### ISSUE THREAD

**Issue by olesmartyniuk** [olesmartyniuk/russian-sites-status-ui#14]
Пропоную вдосконалити дизайн сторінки з деталями про сайт.

Необхідно додати:
1. Посилання на API, що повертає дані. Повинно відкриватись в новому вікні. Шаблон URL: https://russian-sites-status-api.herokuapp.com/api/status/:siteId
2. Кнопку назад перемістити вгору, так як список регіонів може бути великим.
3. Додати колонку з датою останньої перевірки
4. Прибрати колонку з описом регіону, достатньо тільки назви.
5. Зверстати в одному стилі зі списком сайтів

![image](https://user-images.githubusercontent.com/11502936/156187604-05f3cf82-8b94-4772-987e-00d6a99825d0.png)

**Comment by Pavlo-0** [comment]
done
