### ISSUE TITLE
Оптимізація під пошукові системи

### ISSUE THREAD

**Issue by olesmartyniuk** [olesmartyniuk/russian-sites-status-ui#22]
Необхідно модифікувати сайт, щоб він добре індексувався і швидко знаходився в Google по ключовим словам зі списку нижче.

- статус сайту
- статус російського сайту
- DDOS російських сайтів
- перевріити сайт доступний
- перевірити доступність сайту
- список сайтів для DOS атаки
- софт для атаки
- атака російських стайтів

- статус сайта
- статус русского сайта
- DDOS русских сайтов
- проверить сайт доступен
- проверить доступность сайта
- список сайто для DOS атаки
- софт для атаки
- атака русских сайтов

- site status
- russian site status
- list sites for attack
- DDOS russian site

Також можна зареєструвати його в різних реєстрах вручну.

**Comment by eugene-can** [comment]
Google search stat info should be visible here: 
https://search.google.com/search-console?resource_id=sc-domain%3Amordor-sites-status.info

**Comment by eugene-can** [comment]
Some info here: https://www.youtube.com/watch?v=N4PmE3LysUM&list=PLKoqnv2vTMUOnQn-lNDfT38X9gA_CHxTo&index=1

**Comment by eugene-can** [comment]
Need to make all links are crawlable: https://support.google.com/webmasters/answer/9112205
